import clsx from 'clsx'
import type {Metadata} from 'next'
import {Roboto} from 'next/font/google'

import '@/shared/style/global.scss'

import Header from '@/components/header'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

const roboto = Roboto({
	weight: ['100', '300', '400', '500', '700', '900'],
	subsets: ['cyrillic'],
})

export default function RootLayout({children}: {children: React.ReactNode}) {
	return (
		<html>
			<body>
				<div className={clsx(roboto.className, 'wrapper')}>
					<Header />
					{children}
				</div>
			</body>
		</html>
	)
}
